name: just_audio_example
description: Demonstrates how to use the just_audio plugin.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  audio_session: ^0.1.19
  rxdart: ^0.27.7
  just_audio_mpv: ^0.1.6
  just_audio_windows: ^0.2.0
  audio_player:
    path: ../


dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.16.4
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true

  assets:
    - audio/
